name: Test 

on:
  # For testing workflows
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: parse
        uses: ./.github/actions/parse.yml
        with:
          scripts: example.sh
