name: Test 

on:
  # For testing workflows
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install redocly
        id: redocly
        run: npm i -g @redocly/cli@latest
