name: Test 

on:
  # For testing workflows
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Parse
        uses: ./.github/actions/parse
        with:
          scripts: example.sh
