name: Test 

on:
  # For testing workflows
  push

jobs:
  sha:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Identify Service"
        id: service
        run: echo "service=${{ github.ref_name }}" | sed 's/dev\///' >> $GITHUB_OUTPUT
      - name: "Print Service"
        run: echo ${{ steps.service.outputs.service }}
