name: Test 

on:
  # For testing workflows
  push:
    branches: master

jobs:
  sha:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Get SHA"
        id: sha
        run: git log -n 1 --format="%h" | xargs echo "sha=" | sed 's/ //' >> $GITHUB_OUTPUT
      - name: "Print SHA"
        run: echo ${{ steps.sha.outputs.sha }}
      - name: "Print Github SHA"
        run: echo ${{ github.sha }}
